pipeline:
  name: http-helm-pipeline
  identifier: httphelmpipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dev
        identifier: dev
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: httphelm
            serviceInputs:
              serviceDefinition:
                type: NativeHelm
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: devenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: devinfra
          execution:
            steps:
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: stage
        identifier: stage
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          environment:
            environmentRef: stageenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: stageinfra
          execution:
            steps:
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
          service:
            useFromStage:
              stage: dev
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: manual-approval
        identifier: manualapproval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: approver-task
                  identifier: approvertask
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - _project_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
              - step:
                  type: Email
                  name: Email_deploy
                  identifier: Email_deploy
                  spec:
                    to: talktopierremathieu@gmail.com
                    cc: ""
                    subject: Prod deployment
                    body: New release is being deployed to production
                  timeout: 10m
        tags: {}
    - stage:
        name: prod
        identifier: prod
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          environment:
            environmentRef: prodenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: prodinfra
          execution:
            steps:
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
          service:
            useFromStage:
              stage: dev
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
